// Code generated by "enumer --values --type=Platform --linecomment --output platform_string.go --json --yaml --sql"; DO NOT EDIT.

package decentralized

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _PlatformName = "Unknown1inchAAVEAavegotchiCowCrossbellCurveENSFarcasterHighlightIQWikiKiwiStandLensLidoLooksRareMattersMirrorOpenSeaOptimismParagraphRSS3SAVMStargateUniswapVSL"

var _PlatformIndex = [...]uint8{0, 7, 12, 16, 26, 29, 38, 43, 46, 55, 64, 70, 79, 83, 87, 96, 103, 109, 116, 124, 133, 137, 141, 149, 156, 159}

const _PlatformLowerName = "unknown1inchaaveaavegotchicowcrossbellcurveensfarcasterhighlightiqwikikiwistandlenslidolooksraremattersmirroropenseaoptimismparagraphrss3savmstargateuniswapvsl"

func (i Platform) String() string {
	if i >= Platform(len(_PlatformIndex)-1) {
		return fmt.Sprintf("Platform(%d)", i)
	}
	return _PlatformName[_PlatformIndex[i]:_PlatformIndex[i+1]]
}

func (Platform) Values() []string {
	return PlatformStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PlatformNoOp() {
	var x [1]struct{}
	_ = x[PlatformUnknown-(0)]
	_ = x[Platform1Inch-(1)]
	_ = x[PlatformAAVE-(2)]
	_ = x[PlatformAavegotchi-(3)]
	_ = x[PlatformCow-(4)]
	_ = x[PlatformCrossbell-(5)]
	_ = x[PlatformCurve-(6)]
	_ = x[PlatformENS-(7)]
	_ = x[PlatformFarcaster-(8)]
	_ = x[PlatformHighlight-(9)]
	_ = x[PlatformIQWiki-(10)]
	_ = x[PlatformKiwiStand-(11)]
	_ = x[PlatformLens-(12)]
	_ = x[PlatformLido-(13)]
	_ = x[PlatformLooksRare-(14)]
	_ = x[PlatformMatters-(15)]
	_ = x[PlatformMirror-(16)]
	_ = x[PlatformOpenSea-(17)]
	_ = x[PlatformOptimism-(18)]
	_ = x[PlatformParagraph-(19)]
	_ = x[PlatformRSS3-(20)]
	_ = x[PlatformSAVM-(21)]
	_ = x[PlatformStargate-(22)]
	_ = x[PlatformUniswap-(23)]
	_ = x[PlatformVSL-(24)]
}

var _PlatformValues = []Platform{PlatformUnknown, Platform1Inch, PlatformAAVE, PlatformAavegotchi, PlatformCow, PlatformCrossbell, PlatformCurve, PlatformENS, PlatformFarcaster, PlatformHighlight, PlatformIQWiki, PlatformKiwiStand, PlatformLens, PlatformLido, PlatformLooksRare, PlatformMatters, PlatformMirror, PlatformOpenSea, PlatformOptimism, PlatformParagraph, PlatformRSS3, PlatformSAVM, PlatformStargate, PlatformUniswap, PlatformVSL}

var _PlatformNameToValueMap = map[string]Platform{
	_PlatformName[0:7]:          PlatformUnknown,
	_PlatformLowerName[0:7]:     PlatformUnknown,
	_PlatformName[7:12]:         Platform1Inch,
	_PlatformLowerName[7:12]:    Platform1Inch,
	_PlatformName[12:16]:        PlatformAAVE,
	_PlatformLowerName[12:16]:   PlatformAAVE,
	_PlatformName[16:26]:        PlatformAavegotchi,
	_PlatformLowerName[16:26]:   PlatformAavegotchi,
	_PlatformName[26:29]:        PlatformCow,
	_PlatformLowerName[26:29]:   PlatformCow,
	_PlatformName[29:38]:        PlatformCrossbell,
	_PlatformLowerName[29:38]:   PlatformCrossbell,
	_PlatformName[38:43]:        PlatformCurve,
	_PlatformLowerName[38:43]:   PlatformCurve,
	_PlatformName[43:46]:        PlatformENS,
	_PlatformLowerName[43:46]:   PlatformENS,
	_PlatformName[46:55]:        PlatformFarcaster,
	_PlatformLowerName[46:55]:   PlatformFarcaster,
	_PlatformName[55:64]:        PlatformHighlight,
	_PlatformLowerName[55:64]:   PlatformHighlight,
	_PlatformName[64:70]:        PlatformIQWiki,
	_PlatformLowerName[64:70]:   PlatformIQWiki,
	_PlatformName[70:79]:        PlatformKiwiStand,
	_PlatformLowerName[70:79]:   PlatformKiwiStand,
	_PlatformName[79:83]:        PlatformLens,
	_PlatformLowerName[79:83]:   PlatformLens,
	_PlatformName[83:87]:        PlatformLido,
	_PlatformLowerName[83:87]:   PlatformLido,
	_PlatformName[87:96]:        PlatformLooksRare,
	_PlatformLowerName[87:96]:   PlatformLooksRare,
	_PlatformName[96:103]:       PlatformMatters,
	_PlatformLowerName[96:103]:  PlatformMatters,
	_PlatformName[103:109]:      PlatformMirror,
	_PlatformLowerName[103:109]: PlatformMirror,
	_PlatformName[109:116]:      PlatformOpenSea,
	_PlatformLowerName[109:116]: PlatformOpenSea,
	_PlatformName[116:124]:      PlatformOptimism,
	_PlatformLowerName[116:124]: PlatformOptimism,
	_PlatformName[124:133]:      PlatformParagraph,
	_PlatformLowerName[124:133]: PlatformParagraph,
	_PlatformName[133:137]:      PlatformRSS3,
	_PlatformLowerName[133:137]: PlatformRSS3,
	_PlatformName[137:141]:      PlatformSAVM,
	_PlatformLowerName[137:141]: PlatformSAVM,
	_PlatformName[141:149]:      PlatformStargate,
	_PlatformLowerName[141:149]: PlatformStargate,
	_PlatformName[149:156]:      PlatformUniswap,
	_PlatformLowerName[149:156]: PlatformUniswap,
	_PlatformName[156:159]:      PlatformVSL,
	_PlatformLowerName[156:159]: PlatformVSL,
}

var _PlatformNames = []string{
	_PlatformName[0:7],
	_PlatformName[7:12],
	_PlatformName[12:16],
	_PlatformName[16:26],
	_PlatformName[26:29],
	_PlatformName[29:38],
	_PlatformName[38:43],
	_PlatformName[43:46],
	_PlatformName[46:55],
	_PlatformName[55:64],
	_PlatformName[64:70],
	_PlatformName[70:79],
	_PlatformName[79:83],
	_PlatformName[83:87],
	_PlatformName[87:96],
	_PlatformName[96:103],
	_PlatformName[103:109],
	_PlatformName[109:116],
	_PlatformName[116:124],
	_PlatformName[124:133],
	_PlatformName[133:137],
	_PlatformName[137:141],
	_PlatformName[141:149],
	_PlatformName[149:156],
	_PlatformName[156:159],
}

// PlatformString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PlatformString(s string) (Platform, error) {
	if val, ok := _PlatformNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PlatformNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Platform values", s)
}

// PlatformValues returns all values of the enum
func PlatformValues() []Platform {
	return _PlatformValues
}

// PlatformStrings returns a slice of all String values of the enum
func PlatformStrings() []string {
	strs := make([]string, len(_PlatformNames))
	copy(strs, _PlatformNames)
	return strs
}

// IsAPlatform returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Platform) IsAPlatform() bool {
	for _, v := range _PlatformValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Platform
func (i Platform) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Platform
func (i *Platform) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Platform should be a string, got %s", data)
	}

	var err error
	*i, err = PlatformString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Platform
func (i Platform) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Platform
func (i *Platform) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = PlatformString(s)
	return err
}

func (i Platform) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Platform) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Platform: %[1]T(%[1]v)", value)
	}

	val, err := PlatformString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
