// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)

// Index is the predicate function for index builders.
type Index func(*sql.Selector)
