# Default configuration file for the RSS3 Node.
environment: production

discovery:
  operator:
    evm_address: 0x...address
    signature: 0x...signature
  server:
    endpoint: https://your.node.com
    global_indexer_endpoint: https://gi.rss3.io
    access_token: your_access_token

database:
  uri: postgres://postgres:password@localhost:5432/postgres

redis:
  endpoint: localhost:6379
  username:
  password:

stream:
  enable: false
  uri: localhost:9092

observability:
  opentelemetry:
    metrics:
      enable: false
      endpoint: 0.0.0.0:9090
    traces:
      enable: false
      endpoint: localhost:4318
      insecure: true

endpoints:
  vsl:
    url: https://rpc.rss3.io

component:
  rss:
    id: rsshub-core
    network: rsshub
    worker: core
    endpoint: https://your.rsshub.com/
    parameters:
      authentication:
        access_key:
  ai:
    id: agentdata-core
    worker: core
    endpoint: https://your.agentdata.com/
    parameters:
      agentdata_db_url:
      openai_api_key:
      ollama_host:
      kaito_api_token:
      twitter:
        bearer_token:
        api_key:
        api_secret:
        access_token:
        access_token_secret:
