// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FeedsColumns holds the columns for the "feeds" table.
	FeedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "chain", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString},
		{Name: "from", Type: field.TypeString},
		{Name: "to", Type: field.TypeString},
		{Name: "tag", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "index", Type: field.TypeInt, Default: 0},
		{Name: "total_actions", Type: field.TypeInt, Default: 0},
		{Name: "actions", Type: field.TypeJSON},
		{Name: "fee_value", Type: field.TypeFloat64},
		{Name: "fee_token", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FeedsTable holds the schema information for the "feeds" table.
	FeedsTable = &schema.Table{
		Name:       "feeds",
		Columns:    FeedsColumns,
		PrimaryKey: []*schema.Column{FeedsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "feed_platform",
				Unique:  false,
				Columns: []*schema.Column{FeedsColumns[2]},
			},
			{
				Name:    "feed_tag_type",
				Unique:  false,
				Columns: []*schema.Column{FeedsColumns[5], FeedsColumns[6]},
			},
			{
				Name:    "feed_timestamp",
				Unique:  false,
				Columns: []*schema.Column{FeedsColumns[13]},
			},
			{
				Name:    "feed_total_actions",
				Unique:  false,
				Columns: []*schema.Column{FeedsColumns[9]},
			},
		},
	}
	// IndexesColumns holds the columns for the "indexes" table.
	IndexesColumns = []*schema.Column{
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "feed_id", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString},
		{Name: "chain", Type: field.TypeString},
		{Name: "platform", Type: field.TypeString},
		{Name: "tag", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "direction", Type: field.TypeString},
		{Name: "index", Type: field.TypeInt, Default: 0},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// IndexesTable holds the schema information for the "indexes" table.
	IndexesTable = &schema.Table{
		Name:       "indexes",
		Columns:    IndexesColumns,
		PrimaryKey: []*schema.Column{IndexesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FeedsTable,
		IndexesTable,
	}
)

func init() {
}
