openapi: 3.0.3
info:
  title: Node API
  description: RSS3 Node API, data query services provided.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:80
    description: Local development server
tags:
  - name: RSS
    description: Retrieve the details of RSS activities.
  - name: Decentralized
    description: Retrieve the details of decentralized activities.
  - name: Federated
    description: Retrieve the details of federated activities.
  - name: AI
    description: Retrieve the details of AI data.
paths:
  /decentralized/tx/{id}:
    $ref: "./path/decentralized/tx.yaml"
  /decentralized/{account}:
    $ref: "./path/decentralized/account.yaml"
  /decentralized/accounts:
    $ref: "./path/decentralized/accounts.yaml"
  /decentralized/network/{network}:
    $ref: "./path/decentralized/network.yaml"
  /decentralized/platform/{platform}:
    $ref: "./path/decentralized/platform.yaml"
  /decentralized/metadata:
    $ref: "./path/decentralized/metadata.yaml"

  /federated/tx/{id}:
    $ref: "./path/federated/tx.yaml"
  /federated/{account}:
    $ref: "./path/federated/account.yaml"
  /federated/accounts:
    $ref: "./path/federated/accounts.yaml"
  /federated/network/{network}:
    $ref: "./path/federated/network.yaml"
  /federated/platform/{platform}:
    $ref: "./path/federated/platform.yaml"

  # Rss route
  /rss/{path}:
    $ref: "./path/rss.yaml"

  # AI route
  /agentdata/{path}:
      $ref: "./path/ai.yaml"

  # Operator route
  /operators:
    $ref: "./path/home.yaml"
  /operators/activity_count:
    $ref: "./path/activity_count.yaml"
  /operators/workers_status:
    $ref: "./path/workers_status.yaml"
  /operators/info:
    $ref: "./path/info.yaml"

  # Info routes without auth
  /networks/config:
    $ref: "./path/networks/config.yaml"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
